[project]
authors = ["ControlNet <smczx@hotmail.com>"]
channels = ["pytorch", "nvidia/label/cuda-11.8.0", "anaconda", "conda-forge"]
description = "Official implementation for HYDRA."
name = "hydra_vl4ai"
platforms = ["linux-64", "win-64"]
version = "0.0.0"
channel-priority = "disabled"

[tasks]
executor = "python -m hydra_vl4ai.executor --base_config config/okvqa.yaml --model_config config/model_config_1gpu.yaml"
download_model = "python -m hydra_vl4ai.download_model --base_config config/okvqa.yaml --model_config config/model_config_1gpu.yaml"

[build-dependencies]
setuptools = "*"
cmake = "*"
ninja = "*"

[pypi-options]
no-build-isolation = ["maskrcnn_benchmark", "segment_anything", "groundingdino", "llava", "hydra_vl4ai"]

[dependencies]
python = { version = "3.11.*", channel = "anaconda" }
pytorch = { version = "==2.1.2", channel = "pytorch" }
torchvision = { version = "==0.16.2", channel = "pytorch" }
torchaudio = { version = "==2.1.2", channel = "pytorch" }
pytorch-cuda = { version = "11.8.*", channel = "pytorch" }
cuda = { version = "==11.8.0", channel = "nvidia/label/cuda-11.8.0" }
cuda-libraries-dev = { version = "==11.8.0", channel = "nvidia/label/cuda-11.8.0" }
cuda-version = "==11.8"
markupsafe = ">2.0,<3.0"
numpy = "<2.0"
ipywidgets = ">=8.1.5,<9"
ipykernel = ">=6.29.5,<7"

[pypi-dependencies]
fastapi = "*"
uvicorn = "*"
starlette = "*"
openai = "*"
websockets = "~=11.0"
tensorneko_util = ">=0.3.20,<0.4"
tensorneko = ">=0.3.20,<0.4"
requests = "~=2.0"
pillow = "~=10.0"
word2number = "~=1.0"
python_dateutil = "~=2.8.0"
timm = "==0.9.16"
transformers = "~=4.43.0"
tokenizers = "~=0.19.0"
chardet = "~=5.2.0"
python-dotenv = "~=1.0.0"
opencv-python = "~=4.9.0"
accelerate = "~=0.27.0"
bitsandbytes = "==0.38.1"
nltk = "==3.8.1"
pydantic = "~=2.0"
yacs = "==0.1.8"
pycocotools = "==2.0.6"
prettytable = "==3.4.1"
ftfy = "==6.1.1"
torchmetrics = "==1.4.0.post0"
scipy = "==1.14.1"
gdown = "==5.2.0"
rich = "==13.7.1"
ollama = "~=0.3.0"
protobuf = "~=3.19.0"
gradio = ">=5.0,<5.12"
maskrcnn_benchmark = { path = "module_repos/GLIP", editable = true }
segment_anything = { path = "module_repos/Grounded-Segment-Anything/segment_anything", editable = true }
groundingdino = { path = "module_repos/Grounded-Segment-Anything/GroundingDINO", editable = true }
llava = { path = "module_repos/LLaVA", editable = true }
hydra_vl4ai = { path = ".", editable = true }
