[project]
authors = ["ControlNet <smczx@hotmail.com>"]
channels = ["pytorch", "nvidia/label/cuda-11.8.0", "anaconda", "conda-forge"]
description = "Official implementation for HYDRA."
name = "hydra_vl4ai"
platforms = ["linux-64", "win-64"]
version = "0.0.0"
channel-priority = "disabled"

[tasks]
executor = "python -m hydra_vl4ai.executor --base_config config/okvqa.yaml --model_config config/model_config_1gpu.yaml"
download_model = "python -m hydra_vl4ai.download_model --base_config config/okvqa.yaml --model_config config/model_config_1gpu.yaml"

[build-dependencies]
setuptools = "*"
cmake = "*"
ninja = "*"

[dependencies]
python = { version = "3.11.*", channel = "anaconda" }
pytorch = { version = "==2.1.2", channel = "pytorch" }
torchvision = { version = "==0.16.2", channel = "pytorch" }
torchaudio = { version = "==2.1.2", channel = "pytorch" }
pytorch-cuda = { version = "11.8.*", channel = "pytorch" }
cuda = { version = "==11.8.0", channel = "nvidia/label/cuda-11.8.0" }
cuda-libraries-dev = { version = "==11.8.0", channel = "nvidia/label/cuda-11.8.0" }
cuda-version = "==11.8"
markupsafe = ">2.0,<3.0"
numpy = "<2.0"
pandas = ">=2.2.3,<3"
word2number = ">=1.1, <2"
fastapi = "*"
uvicorn = "*"
starlette = "*"
openai = "*"
websockets = "~=11.0"
requests = "~=2.0"
pillow = "~=10.0"
accelerate = ">=1.1.0,<1.2"
transformers = "~=4.43.0"
pydantic = "~=2.10.0"

[pypi-options]
no-build-isolation = ["maskrcnn_benchmark", "llava", "groundingdino", "segment_anything"]

[pypi-dependencies]
tensorneko = "==0.3.21"
ollama = ">=0.5.1, <0.6"
bitsandbytes = ">=0.45.5, <0.46"
timm = ">=1"
pycocotools = "==2.0.6"
python-dotenv = ">=1,<2"
opencv-python = "~=4.9.0"
scipy = "==1.14.1"
rich = "*"
gradio = ">=5.0,<5.12"
maskrcnn_benchmark = { path = "module_repos/GLIP" }
segment_anything = { path = "module_repos/Grounded-Segment-Anything/segment_anything" }
groundingdino = { path = "module_repos/Grounded-Segment-Anything/GroundingDINO" }
llava = { path = "module_repos/LLaVA" }

# ------- Required by GLIP -------
nltk = "==3.8.1"
yacs = "==0.1.8"
prettytable = "==3.4.1"
ftfy = "==6.1.1"
pipdeptree = ">=2.26.1, <3"

# ------- Required by XVLM -------
gdown = ">=5.2.0, <6"

# ------- Current project -------
hydra_vl4ai = { path = ".", editable = true }
