model_save_path: your-save-path
model_name: testing1
rl_agent_train_mode: True # if training tune True
llm_embedding_dim: 1536 # small, 3072 for large
mlp_hidden_dim: 512
critic_layer_num: 4
critic_lr: 0.0001
train_log_interval: 100
batch_size: 128
update_times: 4
save_interval: 100
learn_starts: 1000
dqn_explore_epsilon: 0.2
dqn_explore_epsilon_decay_rate: 0.02
dqn_explore_epsilon_decay_interval: 100
buffer_size: 100000
training_epoch: 4