model_save_path: ./dqn_model_example
model_name: dataset_nameaokvqa_learn_starts300.pt
rl_agent_train_mode: True # if trainin tune True
llm_embedding_dim: 1536 # small, 3072 for large
mlp_hidden_dim: 512
critic_layer_num: 4
critic_lr: 0.0001
train_log_interval: 1
batch_size: 1
update_times: 2
save_interval: 1
learn_starts: 2
dqn_explore_epsilon: 0.2
dqn_explore_epsilon_decay_rate: 0.02
dqn_explore_epsilon_decay_interval: 100
buffer_size: 100000
training_epoch: 1