dataset: okvqa
task: vqa
prompt: chatgpt-35/okvqa
llm_model: "gpt-4o-mini"  # "gpt-3.5-turbo-0630"
llm_code_model: "gpt-4o-mini"  # "gpt-3.5-turbo-0630"
embedding_model: "text-embedding-3-small"

debug: True
executor_port: 31888
llm_max_retry: 3
planner_max_retry: 5
reasoner_max_retry: 5
num_actions: 5
max_iterations: 7
llm_max_concurrency: 1000
max_concurrent_tasks: 20
ratio_box_area_to_image_area: 0.0
crop_larger_margin: True

vlm_model: "blip2"
vlm_caption_model: "blip2"

grounding_model: grounding_dino
glip_threshold: 0.5
grounding_dino_threshold: 0.4

verify_property_model: xvlm
verify_property_thresh_xvlm: 0.5
verify_property_thresh_clip: 0.5